name: Lint

on:
  pull_request:
    branches: [dev, master, main]
  workflow_dispatch:

jobs:
  lint:
    uses: OpenVoiceOS/gh-automations/.github/workflows/lint.yml@f81c5158260a0f9b21c9d8fbf2a83fa466df89f6
    with:
      ruff: true
      pre_commit: false   # set true if .pre-commit-config.yaml exists
