name: PIP Audit

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  pip_audit:
    uses: OpenVoiceOS/gh-automations/.github/workflows/pip-audit.yml@f81c5158260a0f9b21c9d8fbf2a83fa466df89f6
